set nocompatible
set hidden

set rtp^=$HOME/.vim/pack
set packpath^=$HOME/.vim/pack
packloadall

filetype plugin on
filetype indent on

let g:ale_sign_error = ''
let g:ale_sign_warning = '' 
let g:ale_sign_info = ''
let g:ale_linters = {
\   'cs': ['omnisharp'],
\   'typescript': ['eslint', 'tsserver']
\}
let g:ale_fixers = {
\   'typescript': ['eslint', 'tsserver']
\}

" Look and feel
" Assume DarkBlue theme, then adjust from there
if has("gui_macvim")
	let macvim_skip_colorscheme=1
	let s:blue = '#00008b'
	let s:bright_blue = '#0030ff'
	let s:white = '#ffffff'

	color deeperblue
	set macligatures
	set guifont=HasklugNFM-Med:h22
	execute 'hi Pmenu guifg=' . s:white . ' guibg=' . s:blue
	execute 'hi PmenuSel guifg=' . s:white . ' guibg=' . s:bright_blue
	hi! QuickfixLine gui=NONE
endif

