set nocompatible

set rtp^=$HOME/.vim/pack
set packpath^=$HOME/.vim/pack
packloadall

filetype plugin on
filetype indent on

let g:ale_sign_error = ''
let g:ale_sign_warning = '' 
let g:ale_sign_info = ''

" Look and feel
" Assume DarkBlue theme, then adjust from there
if has("gui_macvim")
	let macvim_skip_colorscheme=1
	color deeperblue
	set macligatures
	" set guifont=HasklugNFM-Med:h22
	set guifont=BigBlueTerm437NF:h22
endif
let s:blue = '#00008b'
let s:bright_blue = '#0030ff'
let s:white = '#ffffff'
execute 'hi Pmenu guifg=' . s:white . ' guibg=' . s:blue
execute 'hi PmenuSel guifg=' . s:white . ' guibg=' . s:bright_blue

